function dir_cleanup

files_keep = {'meas_MID*/recon_*.mat',...
              'roi_wm_*.mat',...
              'mask_*.mat',...
              'meas_MID*/interp2/MagRMS*.mat',...
              'meas_MID*/interp2/PhaseImages*.mat'
              '
              
              

