#! /bin/tcsh -f
# Clear the DISPLAY.
unsetenv DISPLAY  # unset DISPLAY for some shells
# Call MATLAB with the appropriate input and output,
# make it immune to hangups and quits using ''nohup'',
# and run it in the background.
nohup nice +19 matlab -nodisplay -nodesktop -nosplash -r $1 > $2 &
