function roi_s2v2s_test(subject,roi,lr,gp)
% convert a surface ROI to a volume ROI, then convert the volume
% ROI back onto the surface.  Because each surface node can map
% to more than one voxels in the 3d volume and one voxel in the 3d volume 
% can also map to multiple surface nodes, one needs to make sure that the 
% the volume ROI generated from surface ROI are not near surface nodes outside
% the original surface ROI. 
% Parameters:
%
% subject: name of the subject
% roi: prefix of the original surface roi.  The file full name would be
% <roi>.niml.roi.
% lr: 'lh' or 'rh', denoting left or right hemisphere, respectively.
% gp: grid parent volume.  This should correspond to the name of a 3d functional data.


%generate surface dataset
cmd = sprintf('ROI2dataset -prefix %s -of 1D -input %s.niml.roi',roi,roi);
unix(cmd);

% convert to volume dataset
cmd = sprintf(['3dSurf2Vol' ...
             ' -spec ../../segmentation/suma/%s_both.spec' ...
             ' -surf_A %s.smoothwm.asc -surf_B %s.pial.asc' ...
             ' -grid_parent %s' ...
             ' -sv %s_SurfVol_ns_Alnd_Exp+orig' ...
             ' -map_func max -f_steps 10' ...
             ' -prefix %s_s2v' ...
             ' -sdata_1D %s.1D.dset'], ...
              subject,lr,lr,gp,subject,roi,roi);
unix(cmd);


%convert the volume dataset back to the surface volume

cmd = sprintf(['3dVol2Surf' ... 
             ' -spec ../../segmentation/suma/%s_both.spec' ...
             ' -surf_A %s.smoothwm.asc -surf_B %s.pial.asc' ...
             ' -sv %s_SurfVol_ns_Alnd_Exp+orig' ...
             ' -grid_parent %s_s2v+orig' ...  
             ' -map_func max -f_steps 10' ... 
             ' -out_niml %s_s2v2s'], ...
              subject,lr,lr,subject,roi,roi);
          
 unix(cmd);
 
 
 subject = 'Zong';
 lr = 'lh';
 dset = 'malach4_vr';
 cmd = sprintf(['3dVol2Surf' ... 
             ' -spec ../../segmentation/suma/%s_both.spec' ...
             ' -surf_A %s.smoothwm.asc -surf_B %s.pial.asc' ...
             ' -sv %s_SurfVol_ns_Alnd_Exp+orig' ...
             ' -grid_parent %s+orig' ...  
             ' -map_func max -f_steps 10' ... 
             ' -skip_col_1dindex' ...
             ' -skip_col_i' ...
             ' -skip_col_j' ...
             ' -skip_col_k' ...
             ' -skip_col_vals' ...
             ' -out_1D %sb'], ...
              subject,lr,lr,subject,dset,dset);
          unix(cmd);
          
          
 
 
 tic;
 data = textread('testniml.1D','','commentstyle','shell');
 disp(toc);
 
 
 
 
 
 
 
 
 
 
 
 
 
 
          